// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-west-2",
    "aws_content_delivery_bucket": "botanybayng-20190429125938-hostingbucket-qa",
    "aws_content_delivery_bucket_region": "us-west-2",
    "aws_content_delivery_url": "https://d2yahfnnsi20s1.cloudfront.net",
    "aws_cognito_identity_pool_id": "us-west-2:766eefc4-05d5-477c-bb08-3f1ce0e69caf",
    "aws_cognito_region": "us-west-2",
    "aws_user_pools_id": "us-west-2_r9JoptmGT",
    "aws_user_pools_web_client_id": "4i66harf567d743l27jgrafaua",
    "oauth": {
        "domain": "botanybayng-qa.auth.us-west-2.amazoncognito.com",
        "scope": [
            "phone",
            "email",
            "openid",
            "profile",
            "aws.cognito.signin.user.admin"
        ],
        "redirectSignIn": "https://www.majestasaurus.com/heroes/,https://localhost:4200/heroes/",
        "redirectSignOut": "https://majestasaurus.com/,https://localhost:4200/",
        "responseType": "code"
    },
    "federationTarget": "COGNITO_USER_POOLS",
    "aws_dynamodb_all_tables_region": "us-west-2",
    "aws_dynamodb_table_schemas": [
        {
            "tableName": "characters-qa",
            "region": "us-west-2"
        }
    ],
    "aws_mobile_analytics_app_id": "7a07c3c38fca48bd992d07154b56d17c",
    "aws_mobile_analytics_app_region": "us-west-2"
};


export default awsmobile;
